import { Project } from "@/types";

export const projects: Project[] = [
  {
    slug: 'nexthire',
    title: 'NextHire',
    description: 'Full-featured Job Portal built with the MERN stack — JWT auth, role-based dashboards, real-time messaging, interview scheduling, notifications, analytics and CSV export.',
    longDescription: 'NextHire is a comprehensive Job Portal platform built with the MERN stack (MongoDB, Express, React, Node.js). It provides a complete ecosystem for the hiring process — employers can post jobs, review applications, schedule interviews, message candidates and export applicant data, while job seekers track applications, save favorites, view interview invites and chat directly with employers. Backed by JWT authentication with role-based access, server-side validation, rate limiting and Helmet security hardening.',
    technologies: ['MongoDB', 'Express 5', 'React 19', 'Node.js', 'Tailwind CSS v4', 'JWT'],
    category: 'fullstack',
    githubLink: 'https://github.com/brunolopes9/NextHire',
    demoLink: 'https://nexthire-3-frontend.onrender.com/',
    image: '/projects/NextHire/1.png',
    images: ['/projects/NextHire/1.png', '/projects/NextHire/2.png'],
    featured: true,
    highlights: [
      'Role-based authentication for employers and seekers',
      'Real-time messaging and notifications system',
      'Interview scheduling module with calendar view',
      'Analytics dashboards and CSV export',
      'Server-side validation, rate limiting and Helmet security',
    ],
  },
  {
    slug: 'bestcall',
    title: 'BestCall.pt',
    description: 'BestCall\'s first professional corporate website — Figma mockup turned into a pixel-perfect, fully responsive WordPress platform with a custom back-office.',
    longDescription: 'BestCall.pt is a professional corporate website developed for a Portuguese telecommunications company. The project involved translating Figma mockups into a pixel-perfect, fully responsive WordPress platform. A custom theme was built with an integrated back-office for managing invoices, payments, knowledge base articles, job postings and internal tools — empowering non-technical staff to update content without developer intervention. The project demonstrates expertise in client work, design implementation and full-stack WordPress development.',
    technologies: ['WordPress', 'PHP', 'HTML', 'CSS', 'SASS', 'JavaScript'],
    category: 'fullstack',
    githubLink: '',
    demoLink: 'https://bestcall.pt/',
    image: '/projects/Bestcall/1.png',
    images: ['/projects/Bestcall/1.png', '/projects/Bestcall/2.png'],
    featured: true,
    highlights: [
      'Pixel-perfect Figma to WordPress conversion',
      'Custom back-office for business management',
      'Invoice, payment and knowledge base modules',
      'SEO and performance optimized',
    ],
  },
  {
    slug: 'ble-tracking',
    title: 'BLE Worker Tracking System',
    description: 'Real-time worker tracking platform built with Bluetooth Low Energy — originally developed for HUF Portuguesa during a Computer Engineering internship at ESTGV.',
    longDescription: 'A real-time Bluetooth Low Energy (BLE) worker tracking system built for industrial production environments. Monitors worker presence at factory machines using BLE beacons, providing real-time analytics, productivity metrics and alert management through a professional dashboard. Originally developed as a real-world solution for HUF Portuguesa during a Computer Engineering internship at ESTGV, and upgraded to a production-grade platform with 6 dashboard views, MQTT-based architecture and a built-in demo mode for hardware-free demonstrations.',
    technologies: ['Node.js', 'Express', 'Socket.IO', 'MQTT', 'PHP', 'Chart.js', 'BLE'],
    category: 'fullstack',
    githubLink: 'https://github.com/brunolopes9/ble_tracking_system',
    demoLink: 'https://github.com/brunolopes9/ble_tracking_system',
    image: '/projects/BLE/1.png',
    images: ['/projects/BLE/1.png', '/projects/BLE/2.png'],
    featured: true,
    highlights: [
      'Real-time BLE distance calculation with RSSI',
      'MQTT-based decoupled architecture',
      'Productivity analytics and alert workflow',
      'Built-in demo mode for hardware-free demos',
      'CSV/JSON data export',
    ],
  },
  {
    slug: 'ranking-app',
    title: 'RankingApp — Tier List Builder',
    description: 'Full-stack tier list ranking application with drag & drop, Recharts statistics, undo/redo, dark mode and JSON export. React 19 + ASP.NET Core 8.',
    longDescription: 'A full-stack tier-list ranking application built with React 19 and ASP.NET Core 8. Create, visualize and export professional S/A/B/C tier rankings for movies, albums and more. Features intuitive HTML5 drag-and-drop, real-time interactive charts (bar, pie, radar), full undo/redo history with keyboard shortcuts, system-aware dark mode, persistent local storage and a responsive mobile-first layout.',
    technologies: ['React 19', 'ASP.NET Core 8', 'C#', 'Tailwind CSS', 'Recharts', 'Vite 7'],
    category: 'fullstack',
    githubLink: 'https://github.com/brunolopes9/rankingApp',
    demoLink: 'https://github.com/brunolopes9/rankingApp',
    image: '/projects/RankingApp/1.png',
    images: [
      '/projects/RankingApp/1.png',
      '/projects/RankingApp/2.png',
      '/projects/RankingApp/3.png',
      '/projects/RankingApp/4.png',
      '/projects/RankingApp/5.png',
      '/projects/RankingApp/6.png',
    ],
    featured: true,
    highlights: [
      'HTML5 drag-and-drop tier ranking',
      'Real-time charts (bar, pie, radar) with Recharts',
      'Full undo/redo history with keyboard shortcuts',
      'Persistent localStorage and JSON export',
    ],
  },
  {
    slug: 'simple-shop',
    title: 'SimpleShop',
    description: 'Modern full-stack e-commerce platform demonstrating polyglot persistence — MongoDB for catalog, MySQL for users/orders, Redis for sessions and cart.',
    longDescription: 'SimpleShop is a modern full-stack e-commerce platform demonstrating polyglot persistence architecture — using the right database for each use case. Built with Fastify 5 for high-performance HTTP, MongoDB with text search for the product catalog, MySQL with Sequelize transactions for users and orders, and Redis for sessions and shopping cart. Includes a complete admin panel with KPI cards, real-time database health monitoring, full CRUD for products, order management and user impersonation. Authentication uses Argon2 password hashing.',
    technologies: ['Fastify 5', 'MongoDB', 'MySQL', 'Redis', 'Sequelize', 'EJS', 'Argon2'],
    category: 'fullstack',
    githubLink: 'https://github.com/brunolopes9/SimpleShop',
    demoLink: 'https://github.com/brunolopes9/SimpleShop',
    image: '/projects/SimpleShop/1.png',
    images: ['/projects/SimpleShop/1.png', '/projects/SimpleShop/2.png'],
    featured: true,
    highlights: [
      'Polyglot persistence — 3 databases',
      'Argon2 password hashing',
      'Transactional checkout with Sequelize',
      'Full admin panel with health monitoring',
    ],
  },
  {
    slug: 'dontforget',
    title: 'DontForget — Task Manager',
    description: 'Full-stack task manager with multi-channel reminders: Email, SMS via Twilio, browser notifications and webhooks (Slack, Discord, Zapier). Recurring tasks, i18n PT/EN.',
    longDescription: 'DontForget is a professional full-stack task management application with multi-channel reminders — Email (SMTP), SMS (Twilio), browser notifications and webhooks for Slack, Discord, Zapier or any HTTP endpoint. Built with React 19, Redux Toolkit, Express 5 and Tailwind CSS 4. Features recurring tasks (daily/weekly/monthly/yearly), priorities with color-coded indicators, subtasks with progress tracking, full-text search, analytics dashboard, multi-language (EN/PT) and dark mode. Designed to solve a real problem: people forget bills, appointments and daily responsibilities.',
    technologies: ['React 19', 'Redux Toolkit', 'Express 5', 'Tailwind 4', 'Twilio', 'Nodemailer'],
    category: 'fullstack',
    githubLink: 'https://github.com/brunolopes9/myTodo',
    demoLink: 'https://mytodo-frontend-mnvy.onrender.com/',
    image: '/projects/DontForget/1.png',
    images: [
      '/projects/DontForget/1.png',
      '/projects/DontForget/2.png',
      '/projects/DontForget/3.png',
      '/projects/DontForget/4.png',
      '/projects/DontForget/5.png',
    ],
    featured: true,
    highlights: [
      'SMS reminders via Twilio',
      'Email reminders via SMTP / Nodemailer',
      'Browser notifications and webhooks',
      'Recurring tasks with auto-creation',
      'Multi-language EN/PT with auto-detection',
    ],
  },
  {
    slug: 'netcrud',
    title: 'netCRUD — Employee Management',
    description: 'Full-stack Employee Management System with .NET 8 Web API and React 19. Dashboards, CRUD with validation, departments, server-side pagination and CSV export.',
    longDescription: 'A full-stack Employee Management System built with .NET 8 Web API and React 19, designed to demonstrate professional software engineering practices including clean architecture, RESTful API design and modern UI/UX. Features a dashboard with KPI cards, interactive Recharts (donut, bar, area), full CRUD with client and server-side validation, advanced search and filters, sortable columns, server-side pagination, employee active/inactive toggle and CSV export. Built with the Service Layer pattern, DTO-based separation, global exception middleware and Entity Framework Core code-first migrations.',
    technologies: ['.NET 8', 'C#', 'EF Core', 'SQL Server', 'React 19', 'Tailwind 4', 'Recharts'],
    category: 'fullstack',
    githubLink: 'https://github.com/brunolopes9/netCRUD',
    demoLink: 'https://github.com/brunolopes9/netCRUD',
    image: '/projects/NetCRUD/1.png',
    images: [
      '/projects/NetCRUD/1.png',
      '/projects/NetCRUD/2.png',
      '/projects/NetCRUD/3.png',
      '/projects/NetCRUD/4.png',
    ],
    featured: false,
    highlights: [
      'Service Layer pattern with DI',
      'Global exception handling middleware',
      'EF Core code-first migrations + seed data',
      'Server-side pagination + CSV export',
    ],
  },
  {
    slug: 'train-twitter',
    title: 'TrainTweet — Social Platform',
    description: 'Full-featured Twitter/X clone built with React 19. Rich tweet composer, AI chatbot, analytics dashboard, explore, notifications, bookmarks and 6 theme colors.',
    longDescription: 'A full-featured Twitter/X clone built with React 19 and Vite, showcasing modern front-end architecture, responsive design and real-world feature implementation. Includes a rich tweet composer with emoji picker and image attachments, an interactive feed with likes/retweets/bookmarks/replies, an AI-powered chatbot (TweetBot AI) that helps users write tweets and analyze content, a full analytics dashboard with Recharts, explore page with trending topics, notifications, profile pages, bookmarks and a settings panel with 6 accent colors and dark/light theme.',
    technologies: ['React 19', 'Vite 7', 'React Router 7', 'Recharts', 'CSS Modules'],
    category: 'frontend',
    githubLink: 'https://github.com/brunolopes9/TrainTwitter',
    demoLink: 'https://brunolopes9.github.io/TrainTwitter/',
    image: '/projects/TrainTwitter/1.png',
    images: [
      '/projects/TrainTwitter/1.png',
      '/projects/TrainTwitter/2.png',
      '/projects/TrainTwitter/3.png',
    ],
    featured: false,
    highlights: [
      'AI chatbot with typewriter effect',
      'Analytics dashboard with Recharts',
      'Glassmorphism 3-column responsive layout',
      'localStorage persistence',
    ],
  },
  {
    slug: 'typing-speed',
    title: 'TypeMaster Pro',
    description: 'Professional-grade typing speed test built with pure vanilla JavaScript — zero dependencies. Real-time WPM, 3 test modes, canvas charts and dark mode.',
    longDescription: 'TypeMaster Pro is a professional-grade typing speed test application built with pure vanilla JavaScript — zero dependencies, zero frameworks. Features character-by-character live feedback, an animated smooth caret, real-time WPM and accuracy tracking, three test modes (time, words, quotes), a hand-built canvas-rendered WPM chart, test history persisted in localStorage, personal best tracking with confetti, dark/light theme and Web Audio API keystroke sounds — all without a single external dependency.',
    technologies: ['HTML5', 'CSS3', 'Vanilla JS', 'Canvas API', 'Web Audio API'],
    category: 'frontend',
    githubLink: 'https://github.com/brunolopes9/TypingSpeed',
    demoLink: 'https://brunolopes9.github.io/TypingSpeed/',
    image: '/projects/TypingSpeed/1.png',
    images: ['/projects/TypingSpeed/1.png', '/projects/TypingSpeed/2.png'],
    featured: false,
    highlights: [
      'Zero dependencies — pure vanilla JS',
      'Canvas-based WPM chart',
      'Web Audio API keystroke sounds',
      '3 test modes with personal best tracking',
    ],
  },
  {
    slug: 'clock',
    title: 'TimeForge — Time Management Suite',
    description: 'Complete time management suite in vanilla HTML/CSS/JS: SVG analog clock, world clock, stopwatch, countdown, Pomodoro and alarms. Zero dependencies.',
    longDescription: 'TimeForge is a professional, feature-rich time management application built with vanilla HTML, CSS and JavaScript. No frameworks, no dependencies, no build tools. Includes 7 features: an SVG analog clock with smooth animation, a world clock with 30+ cities, a precision stopwatch with lap recording, a countdown timer with circular progress, a full Pomodoro Technique implementation with statistics, unlimited alarms with custom sounds and a fully customizable settings panel with 8 accent colors and dark/light theme. All preferences and stats persist via localStorage.',
    technologies: ['HTML5', 'SVG', 'CSS3', 'Vanilla JS', 'Web Audio API'],
    category: 'frontend',
    githubLink: 'https://github.com/brunolopes9/clock',
    demoLink: 'https://brunolopes9.github.io/clock/',
    image: '/projects/Clock/1.png',
    images: ['/projects/Clock/1.png', '/projects/Clock/2.png'],
    featured: false,
    highlights: [
      '7 features in a single zero-dependency app',
      'SVG analog clock with smooth animation',
      'Pomodoro technique with daily statistics',
      'Web Audio API alarm sounds',
    ],
  },
  {
    slug: 'devlinks',
    title: 'DevLinks',
    description: 'A link aggregator that serves as an online business card, built with vanilla HTML, JavaScript and CSS. Dark/light theme included.',
    longDescription: 'DevLinks is a personal project developed for front-end developer training. It is a link aggregator that can be used as an online business card — perfect for showcasing social profiles and portfolio links in one centralized place. Built with pure vanilla HTML, CSS and JavaScript, it includes a dark/light theme toggle and a clean, minimal design that puts the focus on the content.',
    technologies: ['HTML', 'CSS', 'JavaScript'],
    category: 'frontend',
    githubLink: 'https://github.com/brunolopes9/DevLinks',
    demoLink: 'https://brunolopes9.github.io/DevLinks/',
    image: '/projects/DevLinks/1.png',
    images: ['/projects/DevLinks/1.png', '/projects/DevLinks/2.png', '/projects/DevLinks/3.png'],
    featured: false,
    highlights: [
      'Clean, minimal design',
      'Vanilla JavaScript implementation',
      'Dark / light theme',
      'Social links integration',
    ],
  },
  {
    slug: 'brunofolio',
    title: 'BrunoFolio',
    description: 'A modern, responsive personal portfolio website built with Next.js 15, TypeScript, Tailwind CSS v4 and Framer Motion.',
    longDescription: 'BrunoFolio is a professional portfolio website that showcases modern frontend development practices. Built with Next.js 15 App Router for optimal performance and SEO, TypeScript for type safety, Tailwind CSS v4 for utility-first styling and Framer Motion for smooth animations. Features include dark mode with system preference detection, fully responsive design, blog system, services showcase and dynamic project pages with image carousels.',
    technologies: ['Next.js 15', 'TypeScript', 'Tailwind CSS v4', 'Framer Motion'],
    category: 'frontend',
    githubLink: 'https://github.com/brunolopes9/BrunoFolio',
    demoLink: 'https://bruno-folio-8y1g.vercel.app/',
    image: '/projects/bruno9.png',
    featured: false,
    highlights: [
      'Next.js 15 App Router with TypeScript',
      'Dark mode with system preference detection',
      'Framer Motion scroll-triggered animations',
      'Image carousels on project detail pages',
    ],
  },
];
